CREATE TABLE IF NOT EXISTS Game (
    game_id             INT GENERATED BY DEFAULT AS IDENTITY    NOT NULL ,
    game_name           VARCHAR(250)        NOT NULL UNIQUE,
    game_description    VARCHAR(2400)       Not NULL,
    game_img_url        varchar(2048),

    PRIMARY KEY (game_id)
);