-- Create SCript V1

CREATE TABLE IF NOT EXISTS Game (
    game_id             INT GENERATED BY DEFAULT AS IDENTITY    NOT NULL ,
    game_name           VARCHAR(250)        NOT NULL UNIQUE,
    game_description    VARCHAR(2400)       Not NULL,
    game_img_url        varchar(2048),

    PRIMARY KEY (game_id)
);

CREATE TABLE IF NOT EXISTS GameScore (
    score_id            INT GENERATED BY DEFAULT AS IDENTITY    NOT NULL,
    game_id             INT                                     NOT NULL,
    game_score          Decimal                                 NOT NULL    CHECK (game_score >= 0 AND game_score <= 10),

    PRIMARY KEY (score_id),
    FOREIGN KEY (game_id) REFERENCES Game(game_id)
);