services:
  database:
    image: postgres
    command: -c 'max_connections=100'
    ports:
      - 5001:5432
    restart: always
    volumes:
      - pgdatagamebase:/var/lib/postgresql/data
      - ./scripts/sql:/scripts/sql #Maops sql folder
      - ./scripts/shell/sql-set-up.sh:/docker-entrypoint-initdb.d/sql-set-up.sh #runs initialisation scrips if  database doss sent exist
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: GameBaseDb
      #remember to make this environmental secrets /|\
      #secret looks like this:
      #Host=localhost\;Database=GameBaseDb\;User Id=postgres\;Password=postgres\;Port=5001
      #jdbc:postgresql://localhost:5001/GameBaseDb?user=postgres&password=postgres
    networks:
      - game_base_network

  gateway:
    build:
      context: .
      dockerfile: Apps/gateway/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - game_base_network

  featurehub:
    image: featurehub/party-server:latest
    restart: always
    ports:
      - 4085:8085
    volumes:
      - featurehub-h2-data:/db
    networks:
      - game_base_network

  searchengine:
    build:
      context: .
      dockerfile: Apps/SearchEngine/Dockerfile
    ports:
      - 9080:8080
      - 9081:8081
      - 9000:8000 #swagger port
    environment:
      - ASPNETCORE_ENVIRONMENT=Development #TODO Change away from development if this file is used for release
      - ASPNETCORE_URLS=http://+:8000 #Ths allows us 4to use swagger On the API
      - pgconn=Host=database;Database=GameBaseDb;User Id=postgres;Password=postgres;Port=5432 #Connection string for DB
    depends_on:
      - database
      - gateway
    networks:
      - game_base_network
        
  createservice:
    build:
      context: .
      dockerfile: Apps/CreateService/Dockerfile
    ports:
      - 6002:6000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development   
      - ASPNETCORE_URLS=http://+:6000
      - pgconn=Host=database;Database=GameBaseDb;User Id=postgres;Password=postgres;Port=5432 #Connection string for DB
    depends_on:
      - database
      - gateway
    networks:
      - game_base_network

  reviewhandler:
    build:
      context: .
      dockerfile: Apps/reviewHandler/Dockerfile
    ports:
      - 7080:8080
      - 7081:8081
      - 7000:8000 #swagger port
    environment:
      - ASPNETCORE_ENVIRONMENT=Development #TODO Change away from development if this file is used for release
      - ASPNETCORE_URLS=http://+:8000 #Ths allows us 4to use swagger On the API
      - pgconn=Host=database;Database=GameBaseDb;User Id=postgres;Password=postgres;Port=5432 #Connection string for DB
    depends_on:
      - database
      - gateway
    networks:
      - game_base_network

  aidescriptionservice:
    build:
      context: .
      dockerfile: Apps/AiDescriptor/Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - GOOGLE_AI_API_KEY=apikey #TODO Add apikey to secrets
      - FEATUREHUB_TOKEN = featurehubToken #TODO ADD token to secrets
    networks:
      - game_base_network

volumes:
  pgdatagamebase:
  featurehub-h2-data:

networks:
  game_base_network:
    driver: bridge