name: auto-deploy-docker-images
on:
  push:
    branches:
      - main

jobs:
  delivery:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate results of code analysis
          
      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.BD_LIZARD }}

      # Build the Docker image for frontend
     # - name: Build and Push Docker image (web)
      #  run: |
       #   docker build \
      #      -t ghcr.io/emil476m/GameBase-web:staging \
       #     -t ghcr.io/emil476m/GameBase-web:${{ needs.integration.outputs.semver }} \
       #     -f ./Apps/frontend/Dockerfile \
     #       .
      #    docker push ghcr.io/emil476m/GameBase-web --all-tags

      # Build the Docker image for gateway
      - name: Build and Push Docker image (gateway)
        run: |
          docker build \
            -t ghcr.io/emil476m/GameBase-gw:staging \
            -t ghcr.io/emil476m/GameBase-gw:${{ needs.integration.outputs.semver }} \
            -f ./Apps/gateway/Dockerfile \
            .
          docker push ghcr.io/emil476m/GameBase-gw --all-tags

      # Build the Docker image for CreateService
      - name: Build and Push Docker image (CreateService)
        run: |
          docker build \
            -t ghcr.io/emil476m/GameBase-cs:staging \
            -t ghcr.io/emil476m/GameBase-cs:${{ needs.integration.outputs.semver }} \
            -f ./Apps/CreateService/Dockerfile \
            .
          docker push ghcr.io/emil476m/GameBase-cs --all-tags

      # Build the Docker image for SearchEngine
      - name: Build and Push Docker image (SearchEngine)
        run: |
          docker build \
            -t ghcr.io/emil476m/GameBase-se:staging \
            -t ghcr.io/emil476m/GameBase-se:${{ needs.integration.outputs.semver }} \
            -f ./Apps/SearchEngine/Dockerfile \
            .
          docker push ghcr.io/emil476m/GameBase-se --all-tags


      # Build the Docker image for reviewHandler
      - name: Build and Push Docker image (reviewHandler)
        run: |
          docker build \
            -t ghcr.io/emil476m/GameBase-rh:staging \
            -t ghcr.io/emil476m/GameBase-rh:${{ needs.integration.outputs.semver }} \
            -f ./Apps/reviewHandler/Dockerfile \
            .
          docker push ghcr.io/emil476m/GameBase-rh --all-tags

          
   
