name: auto-deploy-docker-images
on:
  push:
    branches:
      - gb/feature/autodeployment

permissions:
  contents: read
  packages: write

jobs:
  delivery:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate results of code analysis
          
      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image for frontend
     # - name: Build and Push Docker image (web)
      #  run: |
       #   docker build \
      #      -t ghcr.io/emil476m/gamebase-web:staging \
       #     -f ./Apps/frontend/Dockerfile \
     #       .
      #    docker push ghcr.io/emil476m/gamebase-web --all-tags

      # Build the Docker image for gateway
      - name: Build and Push Docker image (gateway)
        run: |
          docker build \
            -t ghcr.io/emil476m/gamebase-gw:staging \
            -f ./Apps/gateway/Dockerfile \
            .
          docker push ghcr.io/emil476m/gamebase-gw --all-tags

      # Build the Docker image for CreateService
      - name: Build and Push Docker image (CreateService)
        run: |
          docker build \
            -t ghcr.io/emil476m/gamebase-cs:staging \
            -f ./Apps/CreateService/Dockerfile \
            .
          docker push ghcr.io/emil476m/gamebase-cs --all-tags

      # Build the Docker image for SearchEngine
      - name: Build and Push Docker image (SearchEngine)
        run: |
          docker build \
            -t ghcr.io/emil476m/gamebase-se:staging \
            -f ./Apps/SearchEngine/Dockerfile \
            .
          docker push ghcr.io/emil476m/gamebase-se --all-tags


      # Build the Docker image for reviewHandler
      - name: Build and Push Docker image (reviewHandler)
        run: |
          docker build \
            -t ghcr.io/emil476m/gamebase-rh:staging \
            -f ./Apps/reviewHandler/Dockerfile \
            .
          docker push ghcr.io/emil476m/gamebase-rh --all-tags

          
   
